# Keras basics

Just trying to understand how to make seq-seq models generally

In [3]:
from tensorflow.keras.preprocessing import timeseries_dataset_from_array

In [4]:
import numpy as np

In [7]:
array = np.arange(100)

In [8]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
sequence_length=1
sequence_stride=9
sampling_rate=1
batch_size=1
shuffle=False

In [14]:
array[-10:]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
data = timeseries_dataset_from_array(data=array[:-10],
                                     targets=array[10:],
                                     sequence_length=sequence_length,
                                     sequence_stride=sequence_stride,
                                     sampling_rate=sampling_rate,
                                     batch_size=batch_size,
                                     shuffle=shuffle)

In [24]:
for i,batch in enumerate(data):
    print(i)
    inputs, targets = batch

0
1
2
3
4
5
6
7
8
9


In [30]:
inputs.shape

TensorShape([1, 1])

In [ ]:
inputs

In [28]:
targets

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([91])>

In [29]:
inputs[0]

<tf.Tensor: shape=(1,), dtype=int64, numpy=array([81])>

In [31]:
inputs[0][0]

<tf.Tensor: shape=(), dtype=int64, numpy=81>